services:
  - type: worker
    name: auza-vachet-nha-cai-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_USERNAME
        value: '@auzasito'
